In [1]:
import os
os.chdir('drive/MyDrive/ColabNotebooks/CANN_Pietro/Test')

FileNotFoundError: ignored

In [1]:
import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [2]:
class DirectionComputer(torch.nn.Module):

  def __init__(self,J=3, *args, **kwargs) -> None:
      super(DirectionComputer,self).__init__(*args, **kwargs)

      self.J = J

      self.main = nn.Sequential(
          
          nn.Linear(7,2*self.J),
          nn.Tanh(),
          nn.Linear(2*self.J,2*self.J),
          nn.Tanh(),
          nn.Linear(2*self.J,3*self.J),
          nn.Unflatten(1,(self.J,3))
        
      )

  def forward(self,f_):

    l_ = self.main(f_)
    l_ = nn.functional.normalize(l_,dim=2)

    return l_


In [6]:
model = DirectionComputer(J=5)
f = torch.rand(10,7)

In [7]:
model(f).shape

torch.Size([10, 5, 3])

In [8]:
model(f)[0]

tensor([[-0.2206, -0.7288,  0.6482],
        [ 0.8522, -0.3577, -0.3817],
        [ 0.3796, -0.5504, -0.7436],
        [-0.8001, -0.5870,  0.1237],
        [ 0.3739, -0.7898,  0.4862]], grad_fn=<SelectBackward0>)

In [10]:
torch.dot(model(f)[1,0],model(f)[1,0])

tensor(1.0000, grad_fn=<DotBackward0>)

In [11]:
pytorch_total_params = sum(p.numel() for p in model.parameters() )

In [12]:
for p  in model.parameters():
  print(p)

Parameter containing:
tensor([[-0.0426,  0.0448,  0.2732, -0.2128, -0.0314, -0.3518, -0.0363],
        [ 0.2952, -0.1646, -0.2155, -0.3557,  0.1608,  0.1221,  0.1907],
        [ 0.3020, -0.1921, -0.2050, -0.2742,  0.3016,  0.2283,  0.0473],
        [ 0.2002, -0.0054,  0.0965,  0.0110,  0.1266, -0.3401,  0.0802],
        [ 0.0978, -0.2233,  0.3490, -0.2380, -0.0226,  0.1760,  0.0893],
        [ 0.1700, -0.0428, -0.3170, -0.1283,  0.0702,  0.2180, -0.2935],
        [ 0.2898, -0.1043,  0.1357,  0.1509, -0.2859, -0.0425,  0.3305],
        [ 0.0533,  0.1895,  0.3732,  0.1228,  0.3198, -0.1774,  0.3537],
        [-0.3461, -0.0038,  0.0170, -0.2271, -0.3149,  0.0874, -0.1829],
        [-0.2659, -0.3156, -0.1318, -0.1098, -0.2678,  0.1483, -0.1723]],
       requires_grad=True)
Parameter containing:
tensor([-0.1453,  0.1500, -0.0608, -0.0312,  0.1623,  0.2644, -0.2931, -0.1243,
        -0.1543,  0.3009], requires_grad=True)
Parameter containing:
tensor([[-5.4656e-02,  2.5222e-01,  1.5951e-01, -

In [ ]:
a = t.repeat(1,1)

RuntimeError: ignored