In [54]:
import os
os.chdir('drive/MyDrive/ColabNotebooks/CANN_Pietro/Test')

FileNotFoundError: ignored

In [55]:
import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [81]:

class GeneralizedStructuralTensorComputer(torch.nn.Module):

  def __init__(self, Vectorize=True, *args, **kwargs) -> None:
      super(GeneralizedStructuralTensorComputer,self).__init__(*args, **kwargs)

      self.Vectorize = Vectorize

  def forward(self,L_,w_):

    if self.Vectorize == True:

      Lgen_ = self.Lgen_Computation_Vec(L_,w_)

    else:

      Lgen_ = self.Lgen_Computation(L_,w_)


    return Lgen_




  def Lgen_Computation(self,L_,w_):

    # w_ --> weight tensor [?,J+1,R]
    # L_ --> structural tensor vector [?,J+1,3,3]
    R = w_.shape[2]
    J = L_.shape[1]
    batchsize = L_.shape[0]


    Lgen_ = torch.zeros((batchsize,R,3,3))

    for data_index,(L,w) in enumerate(zip(L_,w_)):

      Lgen_[data_index,:,:,:] = torch.tensordot(w,L,dims=([0],[0]))

    return Lgen_

  def Lgen_Computation_Vec(self,L_,w_):

    # w_ --> weight tensor [?,J+1,R]
    # L_ --> structural tensor vector [?,J+1,3,3]

    customdot = lambda w,L : torch.tensordot(w,L,dims=([0],[0]))

    vectorized = torch.vmap(customdot)
    Lgen_ = vectorized(w_,L_)

    return Lgen_

In [96]:
L = torch.rand((1,3,3,3))
w = torch.rand(1,3,3) 

In [97]:
model = GeneralizedStructuralTensorComputer(Vectorize=False)
model2 = GeneralizedStructuralTensorComputer()


In [98]:
Lgen = model(L,w)
Lgen2 = model2(L,w)

In [99]:
Lgen == Lgen2

tensor([[[[ True,  True,  True],
          [ True,  True, False],
          [False,  True, False]],

         [[ True,  True,  True],
          [ True,  True,  True],
          [ True,  True,  True]],

         [[ True,  True,  True],
          [ True,  True,  True],
          [ True,  True,  True]]]])

In [100]:
L

tensor([[[[0.7153, 0.1709, 0.7541],
          [0.6949, 0.3245, 0.6983],
          [0.1542, 0.5755, 0.8370]],

         [[0.7937, 0.0743, 0.6775],
          [0.7786, 0.9306, 0.7846],
          [0.4136, 0.0354, 0.2794]],

         [[0.1867, 0.1243, 0.6713],
          [0.7786, 0.7034, 0.3628],
          [0.1347, 0.4476, 0.4295]]]])

In [101]:
w

tensor([[[0.6895, 0.7352, 0.8978],
         [0.2045, 0.3047, 0.6993],
         [0.4023, 0.4206, 0.9611]]])

In [102]:
Lgen

tensor([[[[0.7306, 0.1831, 0.9286],
          [0.9516, 0.6970, 0.7879],
          [0.2451, 0.5841, 0.8071]],

         [[0.8462, 0.2006, 1.0432],
          [1.0756, 0.8180, 0.9051],
          [0.2960, 0.6221, 0.8811]],

         [[1.3767, 0.3248, 1.7960],
          [1.9167, 1.6181, 1.5244],
          [0.5571, 0.9716, 1.3596]]]])

In [103]:
Lgen2

tensor([[[[0.7306, 0.1831, 0.9286],
          [0.9516, 0.6970, 0.7879],
          [0.2451, 0.5841, 0.8071]],

         [[0.8462, 0.2006, 1.0432],
          [1.0756, 0.8180, 0.9051],
          [0.2960, 0.6221, 0.8811]],

         [[1.3767, 0.3248, 1.7960],
          [1.9167, 1.6181, 1.5244],
          [0.5571, 0.9716, 1.3596]]]])