In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import os
os.chdir('drive/MyDrive/ColabNotebooks/CANN_Pietro/Test')

In [2]:
import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [3]:
class StructuralTensorComputer(torch.nn.Module):

  def __init__(self, Vectorize=True, *args, **kwargs) -> None:
      super(StructuralTensorComputer,self).__init__(*args, **kwargs)

      self.Vectorize = Vectorize

  def forward(self,l_):

    if self.Vectorize == True:

      L_ = self.L_Computation_Vec(l_)

    else:

      L_ = self.L_Computation(l_)


    return L_


  def L_Computation(self, l_):

    J = l_.shape[1]
    batchsize = l_.shape[0]

    L_ = torch.zeros((batchsize,J+1,3,3))

    for data_index, l_set in enumerate(l_):

      for l_index, l in enumerate(l_set):

        L_[data_index,l_index,:,:] = torch.tensordot(l,l,dims=0)

      L_[data_index,J,:,:] = torch.eye(3)*1/3

    return L_

  def L_Computation_Vec(self, l_):

    customdot = lambda l : torch.tensordot(l,l,dims=0)

    vectorized = torch.vmap(torch.vmap(customdot))

    L_ = vectorized(l_)

    I = torch.eye(3,3)*1/3
    I = I.repeat(l_.shape[0],1)
    I = torch.reshape(I,(l_.shape[0],1,3,3))

    L_ = torch.cat((L_,I),1)

    return L_

In [79]:
a = torch.rand((10,2,3))

In [80]:
model2=StructuralTensorComputer()


In [81]:
model2(a)

tensor([[[[1.7449e-01, 4.2507e-02, 8.5080e-03],
          [4.2507e-02, 1.0355e-02, 2.0726e-03],
          [8.5080e-03, 2.0726e-03, 4.1484e-04]],

         [[4.1948e-01, 4.9848e-01, 1.2393e-01],
          [4.9848e-01, 5.9236e-01, 1.4727e-01],
          [1.2393e-01, 1.4727e-01, 3.6612e-02]],

         [[3.3333e-01, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 3.3333e-01, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 3.3333e-01]]],


        [[[9.4432e-01, 1.0007e-01, 9.5743e-01],
          [1.0007e-01, 1.0605e-02, 1.0146e-01],
          [9.5743e-01, 1.0146e-01, 9.7072e-01]],

         [[7.9144e-01, 1.5435e-01, 1.3100e-01],
          [1.5435e-01, 3.0101e-02, 2.5548e-02],
          [1.3100e-01, 2.5548e-02, 2.1684e-02]],

         [[3.3333e-01, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 3.3333e-01, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 3.3333e-01]]],


        [[[9.6725e-01, 4.3285e-01, 3.2898e-02],
          [4.3285e-01, 1.9370e-01, 1.4722e-02],
          [3.2898e-02, 1

In [82]:
a.shape

torch.Size([10, 2, 3])

In [83]:
a[0]

tensor([[0.4177, 0.1018, 0.0204],
        [0.6477, 0.7696, 0.1913]])

In [84]:
model2(a)[0]

tensor([[[1.7449e-01, 4.2507e-02, 8.5080e-03],
         [4.2507e-02, 1.0355e-02, 2.0726e-03],
         [8.5080e-03, 2.0726e-03, 4.1484e-04]],

        [[4.1948e-01, 4.9848e-01, 1.2393e-01],
         [4.9848e-01, 5.9236e-01, 1.4727e-01],
         [1.2393e-01, 1.4727e-01, 3.6612e-02]],

        [[3.3333e-01, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 3.3333e-01, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 3.3333e-01]]])

In [86]:
a[0,0,0]*a[0,0,2]

tensor(0.0085)

In [ ]:
a.shape

torch.Size([10, 2, 3])

In [25]:
model2(a).shape

torch.Size([10, 2, 3, 2, 3])

In [67]:
t = torch.eye(3,3)*1/3

In [68]:
a = t.repeat(4,1)

In [69]:
torch.reshape(a,(4,1,3,3))

tensor([[[[0.3333, 0.0000, 0.0000],
          [0.0000, 0.3333, 0.0000],
          [0.0000, 0.0000, 0.3333]]],


        [[[0.3333, 0.0000, 0.0000],
          [0.0000, 0.3333, 0.0000],
          [0.0000, 0.0000, 0.3333]]],


        [[[0.3333, 0.0000, 0.0000],
          [0.0000, 0.3333, 0.0000],
          [0.0000, 0.0000, 0.3333]]],


        [[[0.3333, 0.0000, 0.0000],
          [0.0000, 0.3333, 0.0000],
          [0.0000, 0.0000, 0.3333]]]])