In [2]:
import os
os.chdir('drive/MyDrive/ColabNotebooks/CANN_Pietro/Test')

FileNotFoundError: ignored

In [3]:
import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [18]:
class WeightComputer(torch.nn.Module):

  def __init__(self,J=3, R=5, *args, **kwargs) -> None:
      super(WeightComputer,self).__init__(*args, **kwargs)

      self.J = J+1
      self.R = R

      self.main = nn.Sequential(
          
          nn.Linear(7,2*self.J),
          nn.Tanh(),
          nn.Linear(2*self.J,2*self.J),
          nn.Tanh(),
          nn.Linear(2*self.J,self.J*self.R),
          nn.Unflatten(1,(self.J,self.R))
        
      )

  def forward(self,f_):

    w = self.main(f_)
    w = w*w
    w_ = nn.functional.normalize(w,dim=1,p=1)

    return w_


In [19]:
model = WeightComputer()
f = torch.rand(10,7)

In [20]:
model(f).shape

torch.Size([10, 4, 5])

In [21]:
model(f)[0]

tensor([[2.8679e-01, 9.4934e-01, 2.5324e-01, 9.0647e-01, 4.5638e-03],
        [3.1592e-01, 5.2933e-05, 4.4012e-01, 8.7082e-02, 5.5221e-02],
        [2.6805e-01, 1.1818e-03, 3.0500e-01, 1.2399e-03, 8.8952e-01],
        [1.2924e-01, 4.9427e-02, 1.6416e-03, 5.2059e-03, 5.0691e-02]],
       grad_fn=<SelectBackward0>)

In [26]:
torch.sum(model(f)[0],axis=0)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)

In [ ]:
pytorch_total_params = sum(p.numel() for p in model.parameters() )

In [ ]:
for p  in model.parameters():
  print(p)

Parameter containing:
tensor([[ 0.0178, -0.3368,  0.1046,  0.3700,  0.2961, -0.0797, -0.3758],
        [ 0.1647,  0.1441, -0.2677, -0.0975, -0.2794,  0.1575,  0.0078],
        [ 0.0205, -0.3097, -0.2607, -0.3547, -0.1110,  0.0299,  0.0907],
        [-0.1895, -0.0152,  0.2531,  0.1955, -0.2843, -0.3723, -0.3280],
        [-0.0462, -0.3127,  0.0903, -0.0142, -0.0265,  0.3186,  0.1931],
        [-0.0259,  0.3440,  0.1139,  0.0302, -0.0522,  0.0025,  0.2978]],
       requires_grad=True)
Parameter containing:
tensor([-0.3629, -0.0874,  0.1128,  0.2923,  0.3126, -0.1629],
       requires_grad=True)
Parameter containing:
tensor([[ 0.2866,  0.1856,  0.0497, -0.0220, -0.1554,  0.1823],
        [ 0.1378, -0.3520,  0.2010, -0.2276,  0.2440, -0.3126],
        [ 0.0445, -0.0833, -0.3805,  0.0062, -0.3559, -0.1556],
        [ 0.3083, -0.3522, -0.1448, -0.1797,  0.2031,  0.3170],
        [-0.2399,  0.1890, -0.3346,  0.3871, -0.2733, -0.1602]],
       requires_grad=True)
Parameter containing:
tensor([

In [ ]:
a = t.repeat(1,1)

RuntimeError: ignored