In [1]:
import sys
sys.path.append('/content/drive/MyDrive/ColabNotebooks/CANN_Pietro/WorkspaceCANN')

In [2]:
from CANNLib.ANNLayers.EnergyLayers import PsiComputer
from CANNLib.Datas.Datasets import IsotropicIncompressibleDataset


In [3]:
a = IsotropicIncompressibleDataset(size=1000)
b = IsotropicIncompressibleDataset(seed = 3, size=1000)

In [4]:
a.size

1000

In [5]:
a._F

array([[[1.44349345, 1.02333963, 0.56571094],
        [0.81855878, 1.35841743, 0.5845587 ],
        [1.48536525, 1.12538145, 0.65054048]],

       [[0.53381271, 0.9181252 , 1.05560584],
        [1.19379564, 0.54724166, 1.45997409],
        [1.05897731, 1.00495272, 1.2842771 ]],

       [[1.18726881, 1.06534233, 1.06729481],
        [1.28609021, 1.32883348, 0.52959455],
        [1.39070455, 0.53053332, 0.98480363]],

       ...,

       [[1.4068432 , 0.69065709, 1.00662553],
        [1.18574385, 1.00404534, 0.81647481],
        [1.32707692, 1.43414532, 0.95694766]],

       [[1.02686191, 0.62479436, 1.4189041 ],
        [1.26506991, 0.86107647, 0.53843109],
        [0.96647458, 0.96713789, 0.7591041 ]],

       [[1.11906429, 1.07191995, 1.25737743],
        [1.20610695, 0.85877327, 1.25952418],
        [0.91939704, 1.06825414, 1.23204115]]])

In [6]:
a._C

array([[[4.96002175, 4.26073107, 2.26138591],
        [4.26073107, 4.15900532, 2.10509534],
        [2.26138591, 2.10509534, 1.08494066]],

       [[2.83153699, 2.20762374, 3.66642682],
        [2.20762374, 2.15235729, 3.05877473],
        [3.66642682, 3.05877473, 4.89519568]],

       [[4.99769441, 3.71166255, 3.3178431 ],
        [3.71166255, 3.1822183 , 2.36324844],
        [3.3178431 , 2.36324844, 2.38942679]],

       ...,

       [[5.14632943, 4.06540798, 3.65423743],
        [4.06540798, 3.54188707, 2.8874128 ],
        [3.65423743, 2.8874128 , 2.5956749 ]],

       [[3.58892037, 2.66561365, 2.87182636],
        [2.66561365, 2.06717637, 2.08431196],
        [2.87182636, 2.08431196, 2.87943593]],

       [[3.55228978, 3.21746945, 4.05894204],
        [3.21746945, 3.02767082, 3.74558671],
        [4.05894204, 3.74558671, 4.68532455]]])

In [7]:
a._Psi

array([2.50804588, 2.27396846, 2.79224322, 2.31017867, 2.53468604,
       2.00318387, 3.73817379, 3.17411629, 5.79075466, 4.2704337 ,
       4.14570073, 3.61900944, 1.68129007, 2.7268889 , 3.05665479,
       2.28718709, 1.83499297, 1.7988208 , 1.83237268, 1.87055074,
       3.23142662, 4.06382279, 2.96719977, 2.61839711, 0.74518377,
       1.65431943, 1.28385072, 1.38236949, 2.2416908 , 5.62811041,
       1.37517237, 2.83231412, 2.81510649, 2.56007185, 2.69629691,
       1.14197188, 2.31372348, 2.09201827, 3.69166492, 1.1588069 ,
       2.20923595, 1.69896421, 1.38046559, 3.52190078, 1.5487355 ,
       3.08319472, 1.39230039, 1.090149  , 2.22358735, 1.09502878,
       1.24401602, 2.03056501, 0.92331544, 1.97207917, 3.69364609,
       1.95216918, 5.46357651, 1.51198243, 0.49518108, 1.10601942,
       1.9666423 , 1.36681535, 2.48700278, 3.54544209, 3.01021902,
       2.81671485, 1.68731135, 1.57879181, 2.69008481, 0.41188766,
       2.13756562, 2.47547122, 1.05888365, 1.00973945, 2.94633

In [8]:
a[0]

{'Data': {'C': tensor([[4.9600, 4.2607, 2.2614],
          [4.2607, 4.1590, 2.1051],
          [2.2614, 2.1051, 1.0849]], dtype=torch.float64),
  'f': tensor([1., 1., 1.], dtype=torch.float64)},
 'Psi': tensor(2.5080, dtype=torch.float64)}

In [9]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(a, batch_size=64, shuffle=True)
test_dataloader = DataLoader(b, batch_size=64, shuffle=True)

In [11]:
for i in train_dataloader:
  print(i['Data']['C'].shape)
  print(i['Psi'].shape)

torch.Size([64, 3, 3])
torch.Size([64])
torch.Size([64, 3, 3])
torch.Size([64])
torch.Size([64, 3, 3])
torch.Size([64])
torch.Size([64, 3, 3])
torch.Size([64])
torch.Size([64, 3, 3])
torch.Size([64])
torch.Size([64, 3, 3])
torch.Size([64])
torch.Size([64, 3, 3])
torch.Size([64])
torch.Size([64, 3, 3])
torch.Size([64])
torch.Size([64, 3, 3])
torch.Size([64])
torch.Size([64, 3, 3])
torch.Size([64])
torch.Size([64, 3, 3])
torch.Size([64])
torch.Size([64, 3, 3])
torch.Size([64])
torch.Size([64, 3, 3])
torch.Size([64])
torch.Size([64, 3, 3])
torch.Size([64])
torch.Size([64, 3, 3])
torch.Size([64])
torch.Size([40, 3, 3])
torch.Size([40])
